import type { Metadata } from 'next';
import { fontSans, fontMono } from '@/lib/fonts';
import { Toaster } from '@/components/toast';
import '../style/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${fontSans.variable} ${fontMono.variable}`}>
      <body className='dark font-sans antialiased'>
        {children}
        <Toaster />
      </body>
    </html>
  );
}