import type { Metadata } from 'next';
import { Toaster } from '@/components/toast';

import '../style/global.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="dark">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
