// Import core
import type { Metadata } from 'next';
// Import customs
import '../style/globals.css';
import { ThemeProvider } from '@next-example/components/theme-provider';
import { Toaster } from '@design-system/components/toast';
import { Sonner } from '@design-system/components/sonner';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <Toaster />
          <Sonner />
        </ThemeProvider>
      </body>
    </html>
  );
}
