const { fontFamily } = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './.storybook/**/*.{ts,tsx}',
    './stories/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      brand: {
        50: 'var(--color-brand-50)',
        100: 'var(--color-brand-100)',
        200: 'var(--color-brand-200)',
        300: 'var(--color-brand-300)',
        400: 'var(--color-brand-400)',
        500: 'var(--color-brand-500)',
        600: 'var(--color-brand-600)',
        700: 'var(--color-brand-700)',
        800: 'var(--color-brand-800)',
        900: 'var(--color-brand-900)',
        950: 'var(--color-brand-950)',
      },
      neutral: {
        0: 'var(--color-neutral-0)',
        50: 'var(--color-neutral-50)',
        100: 'var(--color-neutral-100)',
        200: 'var(--color-neutral-200)',
        300: 'var(--color-neutral-300)',
        400: 'var(--color-neutral-400)',
        500: 'var(--color-neutral-500)',
        600: 'var(--color-neutral-600)',
        700: 'var(--color-neutral-700)',
        800: 'var(--color-neutral-800)',
        900: 'var(--color-neutral-900)',
        950: 'var(--color-neutral-950)',
        1000: 'var(--color-neutral-1000)',
      },
      red: {
        50: 'var(--color-red-50)',
        100: 'var(--color-red-100)',
        200: 'var(--color-red-200)',
        300: 'var(--color-red-300)',
        400: 'var(--color-red-400)',
        500: 'var(--color-red-500)',
        600: 'var(--color-red-600)',
        700: 'var(--color-red-700)',
        800: 'var(--color-red-800)',
        900: 'var(--color-red-900)',
        950: 'var(--color-red-950)',
      },
      orange: {
        50: 'var(--color-orange-50)',
        100: 'var(--color-orange-100)',
        200: 'var(--color-orange-200)',
        300: 'var(--color-orange-300)',
        400: 'var(--color-orange-400)',
        500: 'var(--color-orange-500)',
        600: 'var(--color-orange-600)',
        700: 'var(--color-orange-700)',
        800: 'var(--color-orange-800)',
        900: 'var(--color-orange-900)',
        950: 'var(--color-orange-950)',
      },
      amber: {
        50: 'var(--color-amber-50)',
        100: 'var(--color-amber-100)',
        200: 'var(--color-amber-200)',
        300: 'var(--color-amber-300)',
        400: 'var(--color-amber-400)',
        500: 'var(--color-amber-500)',
        600: 'var(--color-amber-600)',
        700: 'var(--color-amber-700)',
        800: 'var(--color-amber-800)',
        900: 'var(--color-amber-900)',
        950: 'var(--color-amber-950)',
      },
      yellow: {
        50: 'var(--color-yellow-50)',
        100: 'var(--color-yellow-100)',
        200: 'var(--color-yellow-200)',
        300: 'var(--color-yellow-300)',
        400: 'var(--color-yellow-400)',
        500: 'var(--color-yellow-500)',
        600: 'var(--color-yellow-600)',
        700: 'var(--color-yellow-700)',
        800: 'var(--color-yellow-800)',
        900: 'var(--color-yellow-900)',
        950: 'var(--color-yellow-950)',
      },
      lime: {
        50: 'var(--color-lime-50)',
        100: 'var(--color-lime-100)',
        200: 'var(--color-lime-200)',
        300: 'var(--color-lime-300)',
        400: 'var(--color-lime-400)',
        500: 'var(--color-lime-500)',
        600: 'var(--color-lime-600)',
        700: 'var(--color-lime-700)',
        800: 'var(--color-lime-800)',
        900: 'var(--color-lime-900)',
        950: 'var(--color-lime-950)',
      },
      green: {
        50: 'var(--color-green-50)',
        100: 'var(--color-green-100)',
        200: 'var(--color-green-200)',
        300: 'var(--color-green-300)',
        400: 'var(--color-green-400)',
        500: 'var(--color-green-500)',
        600: 'var(--color-green-600)',
        700: 'var(--color-green-700)',
        800: 'var(--color-green-800)',
        900: 'var(--color-green-900)',
        950: 'var(--color-green-950)',
      },
      emerald: {
        50: 'var(--color-emerald-50)',
        100: 'var(--color-emerald-100)',
        200: 'var(--color-emerald-200)',
        300: 'var(--color-emerald-300)',
        400: 'var(--color-emerald-400)',
        500: 'var(--color-emerald-500)',
        600: 'var(--color-emerald-600)',
        700: 'var(--color-emerald-700)',
        800: 'var(--color-emerald-800)',
        900: 'var(--color-emerald-900)',
        950: 'var(--color-emerald-950)',
      },
      teal: {
        50: 'var(--color-teal-50)',
        100: 'var(--color-teal-100)',
        200: 'var(--color-teal-200)',
        300: 'var(--color-teal-300)',
        400: 'var(--color-teal-400)',
        500: 'var(--color-teal-500)',
        600: 'var(--color-teal-600)',
        700: 'var(--color-teal-700)',
        800: 'var(--color-teal-800)',
        900: 'var(--color-teal-900)',
        950: 'var(--color-teal-950)',
      },
      cyan: {
        50: 'var(--color-cyan-50)',
        100: 'var(--color-cyan-100)',
        200: 'var(--color-cyan-200)',
        300: 'var(--color-cyan-300)',
        400: 'var(--color-cyan-400)',
        500: 'var(--color-cyan-500)',
        600: 'var(--color-cyan-600)',
        700: 'var(--color-cyan-700)',
        800: 'var(--color-cyan-800)',
        900: 'var(--color-cyan-900)',
        950: 'var(--color-cyan-950)',
      },
      sky: {
        50: 'var(--color-sky-50)',
        100: 'var(--color-sky-100)',
        200: 'var(--color-sky-200)',
        300: 'var(--color-sky-300)',
        400: 'var(--color-sky-400)',
        500: 'var(--color-sky-500)',
        600: 'var(--color-sky-600)',
        700: 'var(--color-sky-700)',
        800: 'var(--color-sky-800)',
        900: 'var(--color-sky-900)',
        950: 'var(--color-sky-950)',
      },
      blue: {
        50: 'var(--color-blue-50)',
        100: 'var(--color-blue-100)',
        200: 'var(--color-blue-200)',
        300: 'var(--color-blue-300)',
        400: 'var(--color-blue-400)',
        500: 'var(--color-blue-500)',
        600: 'var(--color-blue-600)',
        700: 'var(--color-blue-700)',
        800: 'var(--color-blue-800)',
        900: 'var(--color-blue-900)',
        950: 'var(--color-blue-950)',
      },
      indigo: {
        50: 'var(--color-indigo-50)',
        100: 'var(--color-indigo-100)',
        200: 'var(--color-indigo-200)',
        300: 'var(--color-indigo-300)',
        400: 'var(--color-indigo-400)',
        500: 'var(--color-indigo-500)',
        600: 'var(--color-indigo-600)',
        700: 'var(--color-indigo-700)',
        800: 'var(--color-indigo-800)',
        900: 'var(--color-indigo-900)',
        950: 'var(--color-indigo-950)',
      },
      violet: {
        50: 'var(--color-violet-50)',
        100: 'var(--color-violet-100)',
        200: 'var(--color-violet-200)',
        300: 'var(--color-violet-300)',
        400: 'var(--color-violet-400)',
        500: 'var(--color-violet-500)',
        600: 'var(--color-violet-600)',
        700: 'var(--color-violet-700)',
        800: 'var(--color-violet-800)',
        900: 'var(--color-violet-900)',
        950: 'var(--color-violet-950)',
      },
      purple: {
        50: 'var(--color-purple-50)',
        100: 'var(--color-purple-100)',
        200: 'var(--color-purple-200)',
        300: 'var(--color-purple-300)',
        400: 'var(--color-purple-400)',
        500: 'var(--color-purple-500)',
        600: 'var(--color-purple-600)',
        700: 'var(--color-purple-700)',
        800: 'var(--color-purple-800)',
        900: 'var(--color-purple-900)',
        950: 'var(--color-purple-950)',
      },
      fuchsia: {
        50: 'var(--color-fuchsia-50)',
        100: 'var(--color-fuchsia-100)',
        200: 'var(--color-fuchsia-200)',
        300: 'var(--color-fuchsia-300)',
        400: 'var(--color-fuchsia-400)',
        500: 'var(--color-fuchsia-500)',
        600: 'var(--color-fuchsia-600)',
        700: 'var(--color-fuchsia-700)',
        800: 'var(--color-fuchsia-800)',
        900: 'var(--color-fuchsia-900)',
        950: 'var(--color-fuchsia-950)',
      },
      pink: {
        50: 'var(--color-pink-50)',
        100: 'var(--color-pink-100)',
        200: 'var(--color-pink-200)',
        300: 'var(--color-pink-300)',
        400: 'var(--color-pink-400)',
        500: 'var(--color-pink-500)',
        600: 'var(--color-pink-600)',
        700: 'var(--color-pink-700)',
        800: 'var(--color-pink-800)',
        900: 'var(--color-pink-900)',
        950: 'var(--color-pink-950)',
      },
      rose: {
        50: 'var(--color-rose-50)',
        100: 'var(--color-rose-100)',
        200: 'var(--color-rose-200)',
        300: 'var(--color-rose-300)',
        400: 'var(--color-rose-400)',
        500: 'var(--color-rose-500)',
        600: 'var(--color-rose-600)',
        700: 'var(--color-rose-700)',
        800: 'var(--color-rose-800)',
        900: 'var(--color-rose-900)',
        950: 'var(--color-rose-950)',
      },
    },
    spacing: {
      px: '1px',
      0: 'var(--space-0)',
      1: 'var(--space-1)',
      2: 'var(--space-2)',
      3: 'var(--space-3)',
      4: 'var(--space-4)',
      5: 'var(--space-5)',
      6: 'var(--space-6)',
      7: 'var(--space-7',
      8: 'var(--space-8)',
      9: 'var(--space-9)',
      10: 'var(--space-10)',
      11: 'var(--space-11)',
      12: 'var(--space-12)',
      14: 'var(--space-14)',
      16: 'var(--space-16)',
      20: 'var(--space-20)',
      24: 'var(--space-24)',
      28: 'var(--space-28)',
      32: 'var(--space-32)',
      36: 'var(--space-36)',
      40: 'var(--space-40)',
      44: 'var(--space-44)',
      48: 'var(--space-48)',
      52: 'var(--space-52)',
      56: 'var(--space-56)',
      60: 'var(--space-60)',
      64: 'var(--space-64)',
      72: 'var(--space-72)',
      80: 'var(--space-80)',
      96: 'var(--space-96)',
    },
    screens: {
      xs: '390px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      backgroundColor: {
        background: 'var(--color-bg-background)',
        card: 'var(--color-bg-card)',
        subtle: 'var(--color-bg-subtle)',
        muted: 'var(--color-bg-muted)',
        inverse: 'var(--color-bg-inverse)',
        elevated: 'var(--color-bg-elevated)',
        mask: 'var(--color-bg-mask)',
        item: 'var(--color-bg-item)',
        'item-hover': 'var(--color-bg-item-hover)',
        'item-selected': 'var(--color-bg-item-selected)',
        brand: 'var(--color-bg-brand-default)',
        'brand-hover': 'var(--color-bg-brand-hover)',
        'brand-active': 'var(--color-bg-brand-active)',
        'brand-subtle': 'var(--color-bg-brand-subtle)',
        'brand-subtlest': 'var(--color-bg-brand-subtlest)',
        danger: 'var(--color-bg-danger-default)',
        'danger-hover': 'var(--color-bg-danger-hover)',
        'danger-active': 'var(--color-bg-danger-active)',
        'danger-subtle': 'var(--color-bg-danger-subtle)',
        'danger-subtlest': 'var(--color-bg-danger-subtlest)',
        warning: 'var(--color-bg-warning-default)',
        'warning-hover': 'var(--color-bg-warning-hover)',
        'warning-active': 'var(--color-bg-warning-active)',
        'warning-subtle': 'var(--color-bg-warning-subtle)',
        'warning-subtlest': 'var(--color-bg-warning-subtlest)',
        border: 'var(--color-border-default)',
        'border-hover': 'var(--color-border-hover)',
      },
      textColor: {
        DEFAULT: 'var(--color-text-default)',
        description: 'var(--color-text-description)',
        placeholder: 'var(--color-text-placeholder)',
        inverse: 'var(--color-text-inverse)',
        brand: 'var(--color-text-brand-default)',
        'brand-hover': 'var(--color-text-brand-hover)',
        'brand-active': 'var(--color-text-brand-active)',
        'brand-strong': 'var(--color-text-brand-strong)',
        'brand-inverse': 'var(--color-text-brand-inverse)',
        danger: 'var(--color-text-danger-default)',
        'danger-hover': 'var(--color-text-danger-hover)',
        'danger-active': 'var(--color-text-danger-active)',
        'danger-strong': 'var(--color-text-danger-strong)',
        'danger-inverse': 'var(--color-text-danger-inverse)',
        warning: 'var(--color-text-warning-default)',
        'warning-hover': 'var(--color-text-warning-hover)',
        'warning-active': 'var(--color-text-warning-active)',
        'warning-strong': 'var(--color-text-warning-strong)',
        'warning-inverse': 'var(--color-text-warning-inverse)',
      },
      borderColor: {
        default: 'var(--color-border-default)',
        hover: 'var(--color-border-hover)',
        brand: 'var(--color-border-brand-default)',
        'brand-hover': 'var(--color-border-brand-hover)',
        'brand-active': 'var(--color-border-brand-active)',
        'brand-subtle': 'var(--color-border-brand-subtle)',
        'brand-subtlest': 'var(--color-border-brand-subtlest)',
        danger: 'var(--color-border-danger-default)',
        'danger-hover': 'var(--color-border-danger-hover)',
        'danger-active': 'var(--color-border-danger-active)',
        'danger-subtle': 'var(--color-border-danger-subtle)',
        'danger-subtlest': 'var(--color-border-danger-subtlest)',
        warning: 'var(--color-border-warning-default)',
        'warning-hover': 'var(--color-border-warning-hover)',
        'warning-active': 'var(--color-border-warning-active)',
        'warning-subtle': 'var(--color-border-warning-subtle)',
        'warning-subtlest': 'var(--color-border-warning-subtlest)',
      },
      ringColor: {
        brand: 'var(--color-border-brand-default)',
        'brand-subtlest': 'var(--color-border-brand-subtlest)',
        'danger-subtlest': 'var(--color-border-danger-subtlest)',
        'warning-subtlest': 'var(--color-border-warning-subtlest)',
      },
      ringOffsetColor: {
        background: 'var(--color-bg-background)',
        elevated: 'var(--color-bg-elevated)',
        brand: 'var(--color-bg-brand-default)',
        danger: 'var(--color-bg-danger-default)',
        warning: 'var(--color-bg-warning-default)',
      },
      stroke: {
        icon: 'var(--color-icon-default)',
        'icon-hover': 'var(--color-icon-hover)',
        'icon-active': 'var(--color-icon-active)',
        'icon-inverse': 'var(--color-icon-inverse)',
        'icon-brand': 'var(--color-icon-brand-default)',
        'icon-brand-hover': 'var(--color-icon-brand-hover)',
        'icon-brand-active': 'var(--color-icon-brand-active)',
        'icon-brand-strong': 'var(--color-icon-brand-strong)',
        'icon-brand-inverse': 'var(--color-icon-brand-inverse)',
        'icon-danger': 'var(--color-icon-danger-default)',
        'icon-danger-hover': 'var(--color-icon-danger-hover)',
        'icon-danger-active': 'var(--color-icon-danger-active)',
        'icon-danger-strong': 'var(--color-icon-danger-strong)',
        'icon-danger-inverse': 'var(--color-icon-danger-inverse)',
        'icon-warning': 'var(--color-icon-warning-default)',
        'icon-warning-hover': 'var(--color-icon-warning-hover)',
        'icon-warning-active': 'var(--color-icon-warning-active)',
        'icon-warning-strong': 'var(--color-icon-warning-strong)',
        'icon-warning-inverse': 'var(--color-icon-warning-inverse)',
      },
      fill: {
        icon: 'var(--color-icon-default)',
        'icon-hover': 'var(--color-icon-hover)',
        'icon-active': 'var(--color-icon-active)',
        'icon-inverse': 'var(--color-icon-inverse)',
        'icon-brand': 'var(--color-icon-brand-default)',
        'icon-brand-hover': 'var(--color-icon-brand-hover)',
        'icon-brand-active': 'var(--color-icon-brand-active)',
        'icon-brand-strong': 'var(--color-icon-brand-strong)',
        'icon-brand-inverse': 'var(--color-icon-brand-inverse)',
        'icon-danger': 'var(--color-icon-danger-default)',
        'icon-danger-hover': 'var(--color-icon-danger-hover)',
        'icon-danger-active': 'var(--color-icon-danger-active)',
        'icon-danger-strong': 'var(--color-icon-danger-strong)',
        'icon-danger-inverse': 'var(--color-icon-danger-inverse)',
        'icon-warning': 'var(--color-icon-warning-default)',
        'icon-warning-hover': 'var(--color-icon-warning-hover)',
        'icon-warning-active': 'var(--color-icon-warning-active)',
        'icon-warning-strong': 'var(--color-icon-warning-strong)',
        'icon-warning-inverse': 'var(--color-icon-warning-inverse)',
      },
      fontFamily: {
        sans: ['var(--font-geist-sans)', ...fontFamily.sans],
        mono: ['var(--font-geist-mono)', ...fontFamily.mono],
      },
      fontSize: {
        'title-screen': [
          '2.25rem',
          {
            lineHeight: '2.5rem',
            letterSpacing: '-2.5%',
            fontWeight: '600',
          },
        ],
        'title-section': [
          '1.875rem',
          {
            lineHeight: '2.25rem',
            letterSpacing: '-1.5%',
            fontWeight: '600',
          },
        ],
        'title-subsection': [
          '1.5rem',
          {
            lineHeight: '2rem',
            letterSpacing: '-1.5%',
            fontWeight: '600',
          },
        ],
        'title-body': [
          '1.125rem',
          {
            lineHeight: '1.75rem',
            letterSpacing: '-1%',
            fontWeight: '600',
          },
        ],
        'title-group': [
          '0.875rem',
          {
            lineHeight: '1.25rem',
            letterSpacing: '1.5%',
            fontWeight: '500',
          },
        ],
        'md-semibold': [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1.25%',
            fontWeight: '600',
          },
        ],
        'md-medium': [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1.25%',
            fontWeight: '500',
          },
        ],
        md: [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1%',
            fontWeight: '400',
          },
        ],
        'lg-semibold': [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '0.5%',
            fontWeight: '600',
          },
        ],
        'lg-medium': [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '0.5%',
            fontWeight: '500',
          },
        ],
        lg: [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '-0.5%',
            fontWeight: '400',
          },
        ],
        'sm-medium': [
          '0.75rem',
          {
            lineHeight: '1rem',
            fontWeight: '500',
          },
        ],
        sm: [
          '0.75rem',
          {
            lineHeight: '1rem',
            fontWeight: '400',
          },
        ],
        xs: [
          '0.5rem',
          {
            lineHeight: '0.75rem',
            fontWeight: '400',
          },
        ],
      },
      width: {
        0: 'var(--size-0)',
        1: 'var(--size-1)',
        2: 'var(--size-2)',
        3: 'var(--size-3)',
        4: 'var(--size-4)',
        5: 'var(--size-5)',
        6: 'var(--size-6)',
        7: 'var(--size-7',
        8: 'var(--size-8)',
        9: 'var(--size-9)',
        10: 'var(--size-10)',
        11: 'var(--size-11)',
        12: 'var(--size-12)',
        14: 'var(--size-14)',
        16: 'var(--size-16)',
        20: 'var(--size-20)',
        24: 'var(--size-24)',
        28: 'var(--size-28)',
        32: 'var(--size-32)',
        36: 'var(--size-36)',
        40: 'var(--size-40)',
        44: 'var(--size-44)',
        48: 'var(--size-48)',
        52: 'var(--size-52)',
        56: 'var(--size-56)',
        60: 'var(--size-60)',
        64: 'var(--size-64)',
        72: 'var(--size-72)',
        80: 'var(--size-80)',
        96: 'var(--size-96)',
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '3/4': '75%',
        full: '100%',
        screen: '100vw',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      },
      minWidth: ({ theme }) => ({
        ...theme('width'),
      }),
      maxWidth: ({ theme }) => ({
        ...theme('width'),
      }),
      height: {
        0: 'var(--size-0)',
        1: 'var(--size-1)',
        2: 'var(--size-2)',
        3: 'var(--size-3)',
        4: 'var(--size-4)',
        5: 'var(--size-5)',
        6: 'var(--size-6)',
        7: 'var(--size-7',
        8: 'var(--size-8)',
        9: 'var(--size-9)',
        10: 'var(--size-10)',
        11: 'var(--size-11)',
        12: 'var(--size-12)',
        14: 'var(--size-14)',
        16: 'var(--size-16)',
        20: 'var(--size-20)',
        24: 'var(--size-24)',
        28: 'var(--size-28)',
        32: 'var(--size-32)',
        36: 'var(--size-36)',
        40: 'var(--size-40)',
        44: 'var(--size-44)',
        48: 'var(--size-48)',
        52: 'var(--size-52)',
        56: 'var(--size-56)',
        60: 'var(--size-60)',
        64: 'var(--size-64)',
        72: 'var(--size-72)',
        80: 'var(--size-80)',
        96: 'var(--size-96)',
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '3/4': '75%',
        full: '100%',
        screen: '100vh',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      },
      minHeight: ({ theme }) => ({
        ...theme('height'),
      }),
      maxHeight: ({ theme }) => ({
        ...theme('height'),
      }),
      borderRadius: {
        none: 'var(--border-radius-none)',
        sm: 'var(--border-radius-sm)',
        DEFAULT: 'var(--border-radius-default)',
        lg: 'var(--border-radius-lg)',
        full: 'var(--border-radius-full)',
      },
      borderWidth: {
        0: 'var(--border-width-0)',
        DEFAULT: 'var(--border-width-1)',
        2: 'var(--border-width-2)',
      },
      opacity: {
        visible: 'var(--opacity-visible)',
        hover: 'var(--opacity-hover)',
        disabled: 'var(--opacity-disabled)',
        invisible: 'var(--opacity-invisible)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      transformOrigin: {
        'top-center': 'top center',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
