name: Build Design Tokens

on:
  push:
    paths:
      - 'design-token/**' # Esegui l'azione solo quando ci sono commit nella cartella design-token

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Usa la versione di Node.js richiesta dal tuo progetto

    - name: Install Dependencies
      run: npm install

    - name: Build Design Tokens
      run: npm run build --prefix design-token # Esegui il comando nella cartella design-token
