const { fontFamily } = require('tailwindcss/defaultTheme');

/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class'],
  content: [
    './storybook/**/*.{ts,tsx}',
    './pages/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
  ],
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      brand: {
        50: 'var(--brand-50)',
        100: 'var(--brand-100)',
        200: 'var(--brand-200)',
        300: 'var(--brand-300)',
        400: 'var(--brand-400)',
        500: 'var(--brand-500)',
        600: 'var(--brand-600)',
        700: 'var(--brand-700)',
        800: 'var(--brand-800)',
        900: 'var(--brand-900)',
        950: 'var(--brand-950)',
      },
      neutral: {
        0: 'var(--neutral-0)',
        50: 'var(--neutral-50)',
        100: 'var(--neutral-100)',
        200: 'var(--neutral-200)',
        300: 'var(--neutral-300)',
        400: 'var(--neutral-400)',
        500: 'var(--neutral-500)',
        600: 'var(--neutral-600)',
        700: 'var(--neutral-700)',
        800: 'var(--neutral-800)',
        900: 'var(--neutral-900)',
        950: 'var(--neutral-950)',
        1000: 'var(--neutral-1000)',
      },
      red: {
        50: 'var(--red-50)',
        100: 'var(--red-100)',
        200: 'var(--red-200)',
        300: 'var(--red-300)',
        400: 'var(--red-400)',
        500: 'var(--red-500)',
        600: 'var(--red-600)',
        700: 'var(--red-700)',
        800: 'var(--red-800)',
        900: 'var(--red-900)',
        950: 'var(--red-950)',
      },
      orange: {
        50: 'var(--orange-50)',
        100: 'var(--orange-100)',
        200: 'var(--orange-200)',
        300: 'var(--orange-300)',
        400: 'var(--orange-400)',
        500: 'var(--orange-500)',
        600: 'var(--orange-600)',
        700: 'var(--orange-700)',
        800: 'var(--orange-800)',
        900: 'var(--orange-900)',
        950: 'var(--orange-950)',
      },
      amber: {
        50: 'var(--amber-50)',
        100: 'var(--amber-100)',
        200: 'var(--amber-200)',
        300: 'var(--amber-300)',
        400: 'var(--amber-400)',
        500: 'var(--amber-500)',
        600: 'var(--amber-600)',
        700: 'var(--amber-700)',
        800: 'var(--amber-800)',
        900: 'var(--amber-900)',
        950: 'var(--amber-950)',
      },
      yellow: {
        50: 'var(--yellow-50)',
        100: 'var(--yellow-100)',
        200: 'var(--yellow-200)',
        300: 'var(--yellow-300)',
        400: 'var(--yellow-400)',
        500: 'var(--yellow-500)',
        600: 'var(--yellow-600)',
        700: 'var(--yellow-700)',
        800: 'var(--yellow-800)',
        900: 'var(--yellow-900)',
        950: 'var(--yellow-950)',
      },
      lime: {
        50: 'var(--lime-50)',
        100: 'var(--lime-100)',
        200: 'var(--lime-200)',
        300: 'var(--lime-300)',
        400: 'var(--lime-400)',
        500: 'var(--lime-500)',
        600: 'var(--lime-600)',
        700: 'var(--lime-700)',
        800: 'var(--lime-800)',
        900: 'var(--lime-900)',
        950: 'var(--lime-950)',
      },
      green: {
        50: 'var(--green-50)',
        100: 'var(--green-100)',
        200: 'var(--green-200)',
        300: 'var(--green-300)',
        400: 'var(--green-400)',
        500: 'var(--green-500)',
        600: 'var(--green-600)',
        700: 'var(--green-700)',
        800: 'var(--green-800)',
        900: 'var(--green-900)',
        950: 'var(--green-950)',
      },
      emerald: {
        50: 'var(--emerald-50)',
        100: 'var(--emerald-100)',
        200: 'var(--emerald-200)',
        300: 'var(--emerald-300)',
        400: 'var(--emerald-400)',
        500: 'var(--emerald-500)',
        600: 'var(--emerald-600)',
        700: 'var(--emerald-700)',
        800: 'var(--emerald-800)',
        900: 'var(--emerald-900)',
        950: 'var(--emerald-950)',
      },
      teal: {
        50: 'var(--teal-50)',
        100: 'var(--teal-100)',
        200: 'var(--teal-200)',
        300: 'var(--teal-300)',
        400: 'var(--teal-400)',
        500: 'var(--teal-500)',
        600: 'var(--teal-600)',
        700: 'var(--teal-700)',
        800: 'var(--teal-800)',
        900: 'var(--teal-900)',
        950: 'var(--teal-950)',
      },
      cyan: {
        50: 'var(--cyan-50)',
        100: 'var(--cyan-100)',
        200: 'var(--cyan-200)',
        300: 'var(--cyan-300)',
        400: 'var(--cyan-400)',
        500: 'var(--cyan-500)',
        600: 'var(--cyan-600)',
        700: 'var(--cyan-700)',
        800: 'var(--cyan-800)',
        900: 'var(--cyan-900)',
        950: 'var(--cyan-950)',
      },
      sky: {
        50: 'var(--sky-50)',
        100: 'var(--sky-100)',
        200: 'var(--sky-200)',
        300: 'var(--sky-300)',
        400: 'var(--sky-400)',
        500: 'var(--sky-500)',
        600: 'var(--sky-600)',
        700: 'var(--sky-700)',
        800: 'var(--sky-800)',
        900: 'var(--sky-900)',
        950: 'var(--sky-950)',
      },
      blue: {
        50: 'var(--blue-50)',
        100: 'var(--blue-100)',
        200: 'var(--blue-200)',
        300: 'var(--blue-300)',
        400: 'var(--blue-400)',
        500: 'var(--blue-500)',
        600: 'var(--blue-600)',
        700: 'var(--blue-700)',
        800: 'var(--blue-800)',
        900: 'var(--blue-900)',
        950: 'var(--blue-950)',
      },
      indigo: {
        50: 'var(--indigo-50)',
        100: 'var(--indigo-100)',
        200: 'var(--indigo-200)',
        300: 'var(--indigo-300)',
        400: 'var(--indigo-400)',
        500: 'var(--indigo-500)',
        600: 'var(--indigo-600)',
        700: 'var(--indigo-700)',
        800: 'var(--indigo-800)',
        900: 'var(--indigo-900)',
        950: 'var(--indigo-950)',
      },
      violet: {
        50: 'var(--violet-50)',
        100: 'var(--violet-100)',
        200: 'var(--violet-200)',
        300: 'var(--violet-300)',
        400: 'var(--violet-400)',
        500: 'var(--violet-500)',
        600: 'var(--violet-600)',
        700: 'var(--violet-700)',
        800: 'var(--violet-800)',
        900: 'var(--violet-900)',
        950: 'var(--violet-950)',
      },
      purple: {
        50: 'var(--purple-50)',
        100: 'var(--purple-100)',
        200: 'var(--purple-200)',
        300: 'var(--purple-300)',
        400: 'var(--purple-400)',
        500: 'var(--purple-500)',
        600: 'var(--purple-600)',
        700: 'var(--purple-700)',
        800: 'var(--purple-800)',
        900: 'var(--purple-900)',
        950: 'var(--purple-950)',
      },
      fuchsia: {
        50: 'var(--fuchsia-50)',
        100: 'var(--fuchsia-100)',
        200: 'var(--fuchsia-200)',
        300: 'var(--fuchsia-300)',
        400: 'var(--fuchsia-400)',
        500: 'var(--fuchsia-500)',
        600: 'var(--fuchsia-600)',
        700: 'var(--fuchsia-700)',
        800: 'var(--fuchsia-800)',
        900: 'var(--fuchsia-900)',
        950: 'var(--fuchsia-950)',
      },
      pink: {
        50: 'var(--pink-50)',
        100: 'var(--pink-100)',
        200: 'var(--pink-200)',
        300: 'var(--pink-300)',
        400: 'var(--pink-400)',
        500: 'var(--pink-500)',
        600: 'var(--pink-600)',
        700: 'var(--pink-700)',
        800: 'var(--pink-800)',
        900: 'var(--pink-900)',
        950: 'var(--pink-950)',
      },
      rose: {
        50: 'var(--rose-50)',
        100: 'var(--rose-100)',
        200: 'var(--rose-200)',
        300: 'var(--rose-300)',
        400: 'var(--rose-400)',
        500: 'var(--rose-500)',
        600: 'var(--rose-600)',
        700: 'var(--rose-700)',
        800: 'var(--rose-800)',
        900: 'var(--rose-900)',
        950: 'var(--rose-950)',
      },
    },
    spacing: {
      px: '1px',
      0: 'var(--0)',
      1: 'var(--1)',
      2: 'var(--2)',
      3: 'var(--3)',
      4: 'var(--4)',
      5: 'var(--5)',
      6: 'var(--6)',
      7: 'var(--7',
      8: 'var(--8)',
      9: 'var(--9)',
      10: 'var(--10)',
      11: 'var(--11)',
      12: 'var(--12)',
      14: 'var(--14)',
      16: 'var(--16)',
      20: 'var(--20)',
      24: 'var(--24)',
      28: 'var(--28)',
      32: 'var(--32)',
      36: 'var(--36)',
      40: 'var(--40)',
      44: 'var(--44)',
      48: 'var(--48)',
      52: 'var(--52)',
      56: 'var(--56)',
      60: 'var(--60)',
      64: 'var(--64)',
      72: 'var(--72)',
      80: 'var(--80)',
      96: 'var(--96)',
    },
    screens: {
      xs: '390px',
      sm: '640px',
      md: '768px',
      lg: '1024px',
      xl: '1280px',
      '2xl': '1536px',
    },
    extend: {
      backgroundColor: {
        background: 'var(--bg-background)',
        card: 'var(--bg-card)',
        subtle: 'var(--bg-subtle)',
        muted: 'var(--bg-muted)',
        inverse: 'var(--bg-inverse)',
        elevated: 'var(--bg-elevated)',
        mask: 'var(--bg-mask)',
        item: 'var(--bg-item)',
        'item-hover': 'var(--bg-item-hover)',
        'item-selected': 'var(--bg-item-selected)',
        brand: 'var(--bg-brand)',
        'brand-hover': 'var(--bg-brand-hover)',
        'brand-active': 'var(--bg-brand-active)',
        'brand-subtle': 'var(--bg-brand-subtle)',
        'brand-subtlest': 'var(--bg-brand-subtlest)',
        danger: 'var(--bg-danger)',
        'danger-hover': 'var(--bg-danger-hover)',
        'danger-active': 'var(--bg-danger-active)',
        'danger-subtle': 'var(--bg-danger-subtle)',
        'danger-subtlest': 'var(--bg-danger-subtlest)',
        warning: 'var(--bg-warning)',
        'warning-hover': 'var(--bg-warning-hover)',
        'warning-active': 'var(--bg-warning-active)',
        'warning-subtle': 'var(--bg-warning-subtle)',
        'warning-subtlest': 'var(--bg-warning-subtlest)',
        border: 'var(--border-border)',
        'border-hover': 'var(--border-hover)',
      },
      textColor: {
        DEFAULT: 'var(--text)',
        description: 'var(--text-description)',
        placeholder: 'var(--text-placeholder)',
        inverse: 'var(--text-inverse)',
        brand: 'var(--text-brand)',
        'brand-hover': 'var(--text-brand-hover)',
        'brand-active': 'var(--text-brand-active)',
        'brand-strong': 'var(--text-brand-strong)',
        'brand-inverse': 'var(--text-brand-inverse)',
        danger: 'var(--text-danger)',
        'danger-hover': 'var(--text-danger-hover)',
        'danger-active': 'var(--text-danger-active)',
        'danger-strong': 'var(--text-danger-strong)',
        'danger-inverse': 'var(--text-danger-inverse)',
        warning: 'var(--text-warning)',
        'warning-hover': 'var(--text-warning-hover)',
        'warning-active': 'var(--text-warning-active)',
        'warning-strong': 'var(--text-warning-strong)',
        'warning-inverse': 'var(--text-warning-inverse)',
      },
      borderColor: {
        border: 'var(--border-border)',
        hover: 'var(--border-hover)',
        brand: 'var(--border-brand)',
        'brand-hover': 'var(--border-brand-hover)',
        'brand-active': 'var(--border-brand-active)',
        'brand-subtle': 'var(--border-brand-subtle)',
        'brand-subtlest': 'var(--border-brand-subtlest)',
        danger: 'var(--border-danger)',
        'danger-hover': 'var(--border-danger-hover)',
        'danger-active': 'var(--border-danger-active)',
        'danger-subtle': 'var(--border-danger-subtle)',
        'danger-subtlest': 'var(--border-danger-subtlest)',
        warning: 'var(--border-warning)',
        'warning-hover': 'var(--border-warning-hover)',
        'warning-active': 'var(--border-warning-active)',
        'warning-subtle': 'var(--border-warning-subtle)',
        'warning-subtlest': 'var(--border-warning-subtlest)',
      },
      ringColor: {
        brand: 'var(--border-brand)',
        'brand-subtlest': 'var(--border-brand-subtlest)',
        'danger-subtlest': 'var(--border-danger-subtlest)',
        'warning-subtlest': 'var(--border-warning-subtlest)',
      },
      ringOffsetColor: {
        background: 'var(--bg-background)',
        elevated: 'var(--bg-elevated)',
        brand: 'var(--bg-brand)',
        danger: 'var(--bg-danger)',
        warning: 'var(--bg-warning)',
      },
      stroke: {
        icon: 'var(--icon)',
        'icon-hover': 'var(--icon-hover)',
        'icon-active': 'var(--icon-active)',
        'icon-inverse': 'var(--icon-inverse)',
        'icon-brand': 'var(--icon-brand)',
        'icon-brand-hover': 'var(--icon-brand-hover)',
        'icon-brand-active': 'var(--icon-brand-active)',
        'icon-brand-strong': 'var(--icon-brand-strong)',
        'icon-brand-inverse': 'var(--icon-brand-inverse)',
        'icon-danger': 'var(--icon-danger)',
        'icon-danger-hover': 'var(--icon-danger-hover)',
        'icon-danger-active': 'var(--icon-danger-active)',
        'icon-danger-strong': 'var(--icon-danger-strong)',
        'icon-danger-inverse': 'var(--icon-danger-inverse)',
        'icon-warning': 'var(--icon-warning)',
        'icon-warning-hover': 'var(--icon-warning-hover)',
        'icon-warning-active': 'var(--icon-warning-active)',
        'icon-warning-strong': 'var(--icon-warning-strong)',
        'icon-warning-inverse': 'var(--icon-warning-inverse)',
      },
      fill: {
        icon: 'var(--icon)',
        'icon-hover': 'var(--icon-hover)',
        'icon-active': 'var(--icon-active)',
        'icon-inverse': 'var(--icon-inverse)',
        'icon-brand': 'var(--icon-brand)',
        'icon-brand-hover': 'var(--icon-brand-hover)',
        'icon-brand-active': 'var(--icon-brand-active)',
        'icon-brand-strong': 'var(--icon-brand-strong)',
        'icon-brand-inverse': 'var(--icon-brand-inverse)',
        'icon-danger': 'var(--icon-danger)',
        'icon-danger-hover': 'var(--icon-danger-hover)',
        'icon-danger-active': 'var(--icon-danger-active)',
        'icon-danger-strong': 'var(--icon-danger-strong)',
        'icon-danger-inverse': 'var(--icon-danger-inverse)',
        'icon-warning': 'var(--icon-warning)',
        'icon-warning-hover': 'var(--icon-warning-hover)',
        'icon-warning-active': 'var(--icon-warning-active)',
        'icon-warning-strong': 'var(--icon-warning-strong)',
        'icon-warning-inverse': 'var(--icon-warning-inverse)',
      },
      fontFamily: {
        sans: ['var(--geist-sans)', ...fontFamily.sans],
        mono: ['var(--geist-mono)', ...fontFamily.mono],
      },
      fontSize: {
        'title-screen': [
          '2.25rem',
          {
            lineHeight: '2.5rem',
            letterSpacing: '-2.5%',
            fontWeight: '600',
          },
        ],
        'title-section': [
          '1.875rem',
          {
            lineHeight: '2.25rem',
            letterSpacing: '-1.5%',
            fontWeight: '600',
          },
        ],
        'title-subsection': [
          '1.5rem',
          {
            lineHeight: '2rem',
            letterSpacing: '-1.5%',
            fontWeight: '600',
          },
        ],
        'title-body': [
          '1.125rem',
          {
            lineHeight: '1.75rem',
            letterSpacing: '-1%',
            fontWeight: '600',
          },
        ],
        'title-group': [
          '0.875rem',
          {
            lineHeight: '1.25rem',
            letterSpacing: '1.5%',
            fontWeight: '500',
          },
        ],
        'md-semibold': [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1.25%',
            fontWeight: '600',
          },
        ],
        'md-medium': [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1.25%',
            fontWeight: '500',
          },
        ],
        md: [
          '0.875rem',
          {
            lineHeight: '1.375rem',
            letterSpacing: '1%',
            fontWeight: '400',
          },
        ],
        'lg-semibold': [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '0.5%',
            fontWeight: '600',
          },
        ],
        'lg-medium': [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '0.5%',
            fontWeight: '500',
          },
        ],
        lg: [
          '1rem',
          {
            lineHeight: '1.5rem',
            letterSpacing: '-0.5%',
            fontWeight: '400',
          },
        ],
        'sm-medium': [
          '0.75rem',
          {
            lineHeight: '1rem',
            fontWeight: '500',
          },
        ],
        sm: [
          '0.75rem',
          {
            lineHeight: '1rem',
            fontWeight: '400',
          },
        ],
      },
      width: {
        0: 'var(--w-0)',
        1: 'var(--w-1)',
        2: 'var(--w-2)',
        3: 'var(--w-3)',
        4: 'var(--w-4)',
        5: 'var(--w-5)',
        6: 'var(--w-6)',
        7: 'var(--w-7',
        8: 'var(--w-8)',
        9: 'var(--w-9)',
        10: 'var(--w-10)',
        11: 'var(--w-11)',
        12: 'var(--w-12)',
        14: 'var(--w-14)',
        16: 'var(--w-16)',
        20: 'var(--w-20)',
        24: 'var(--w-24)',
        28: 'var(--w-28)',
        32: 'var(--w-32)',
        36: 'var(--w-36)',
        40: 'var(--w-40)',
        44: 'var(--w-44)',
        48: 'var(--w-48)',
        52: 'var(--w-52)',
        56: 'var(--w-56)',
        60: 'var(--w-60)',
        64: 'var(--w-64)',
        72: 'var(--w-72)',
        80: 'var(--w-80)',
        96: 'var(--w-96)',
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '3/4': '75%',
        full: '100%',
        screen: '100vw',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      },
      minWidth: ({ theme }) => ({
        ...theme('width'),
      }),
      maxWidth: ({ theme }) => ({
        ...theme('width'),
      }),
      height: {
        0: 'var(--h-0)',
        1: 'var(--h-1)',
        2: 'var(--h-2)',
        3: 'var(--h-3)',
        4: 'var(--h-4)',
        5: 'var(--h-5)',
        6: 'var(--h-6)',
        7: 'var(--h-7',
        8: 'var(--h-8)',
        9: 'var(--h-9)',
        10: 'var(--h-10)',
        11: 'var(--h-11)',
        12: 'var(--h-12)',
        14: 'var(--h-14)',
        16: 'var(--h-16)',
        20: 'var(--h-20)',
        24: 'var(--h-24)',
        28: 'var(--h-28)',
        32: 'var(--h-32)',
        36: 'var(--h-36)',
        40: 'var(--h-40)',
        44: 'var(--h-44)',
        48: 'var(--h-48)',
        52: 'var(--h-52)',
        56: 'var(--h-56)',
        60: 'var(--h-60)',
        64: 'var(--h-64)',
        72: 'var(--h-72)',
        80: 'var(--h-80)',
        96: 'var(--h-96)',
        auto: 'auto',
        '1/2': '50%',
        '1/3': '33.333333%',
        '2/3': '66.666667%',
        '1/4': '25%',
        '3/4': '75%',
        full: '100%',
        screen: '100vh',
        min: 'min-content',
        max: 'max-content',
        fit: 'fit-content',
      },
      minHeight: ({ theme }) => ({
        ...theme('height'),
      }),
      maxHeight: ({ theme }) => ({
        ...theme('height'),
      }),
      borderRadius: {
        none: 'var(--rounded-none)',
        sm: 'var(--rounded-sm)',
        DEFAULT: 'var(--rounded)',
        lg: 'var(--rounded-lg)',
        full: 'var(--rounded-full)',
      },
      borderWidth: {
        0: 'var(--border-0)',
        DEFAULT: 'var(--border)',
        2: 'var(--border-2)',
      },
      opacity: {
        visible: 'var(--opacity-visible)',
        hover: 'var(--opacity-hover)',
        disabled: 'var(--opacity-disabled)',
        invisible: 'var(--opacity-invisible)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: 0 },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: 0 },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
      transformOrigin: {
        'top-center': 'top center',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
};
