/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ['class', '[data-mode="dark"]'],
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    fontFamily: {
      sans: [
        'Inter',
        'ui-sans-serif',
        'system-ui',
        '-apple-system',
        'BlinkMacSystemFont',
        'Segoe UI',
        'Roboto',
        'Helvetica Neue',
        'Arial',
        'Noto Sans',
        'sans-serif',
        'Apple Color Emoji',
        'Segoe UI Emoji',
        'Segoe UI Symbol',
        'Noto Color Emoji',
      ],
      serif: [
        'ui-serif',
        'Georgia',
        'Cambria',
        'Times New Roman',
        'Times',
        'serif',
      ],
      mono: [
        'ui-monospace',
        'SFMono-Regular',
        'Menlo',
        'Monaco',
        'Consolas',
        'Liberation Mono',
        'Courier New',
        'monospace',
      ],
    },
    extend: {
      colors: {
        color: {
          'bg-layout': 'var(--color-bg-layout)',
          'bg-container': 'var(--color-bg-container)',
          'bg-container-subtle': 'var(--color-bg-container-subtle)',
          'bg-container-subtlest': 'var(--color-bg-container-subtlest)',
          'bg-container-disabled': 'var(--color-bg-container-disabled)',
          'bg-container-inverse': 'var(--color-bg-container-inverse)',
          'bg-elevated': 'var(--color-bg-elevated)',
          'bg-mask': 'var(--color-bg-mask)',
          'bg-interactive': 'var(--color-bg-interactive)',
          'bg-interactive-hover': 'var(--color-bg-interactive-hover)',
          'bg-interactive-selected': 'var(--color-bg-interactive-selected)',
          'bg-interactive-selected-hover':
            'var(--color-bg-interactive-selected-hover)',
          'bg-interactive-disabled': 'var(--color-bg-interactive-disabled)',
          'bg-brand': 'var(--color-bg-brand)',
          'bg-brand-hover': 'var(--color-bg-brand-hover)',
          'bg-brand-active': 'var(--color-bg-brand-active)',
          'bg-brand-selected': 'var(--color-bg-brand-selected)',
          'bg-brand-subtle': 'var(--color-bg-brand-subtle)',
          'bg-brand-subtlest': 'var(--color-bg-brand-subtlest)',
          'bg-danger': 'var(--color-bg-danger)',
          'bg-danger-hover': 'var(--color-bg-danger-hover)',
          'bg-danger-active': 'var(--color-bg-danger-active)',
          'bg-danger-selected': 'var(--color-bg-danger-selected)',
          'bg-danger-subtle': 'var(--color-bg-danger-subtle)',
          'bg-danger-subtlest': 'var(--color-bg-danger-subtlest)',
          'bg-warning': 'var(--color-bg-warning)',
          'bg-warning-hover': 'var(--color-bg-warning-hover)',
          'bg-warning-active': 'var(--color-bg-warning-active)',
          'bg-warning-selected': 'var(--color-bg-warning-selected)',
          'bg-warning-subtle': 'var(--color-bg-warning-subtle)',
          'bg-warning-subtlest': 'var(--color-bg-warning-subtlest)',
          'bg-success': 'var(--color-bg-success)',
          'bg-success-hover': 'var(--color-bg-success-hover)',
          'bg-success-active': 'var(--color-bg-success-active)',
          'bg-success-selected': 'var(--color-bg-success-selected)',
          'bg-success-subtle': 'var(--color-bg-success-subtle)',
          'bg-success-subtlest': 'var(--color-bg-success-subtlest)',
          'bg-info': 'var(--color-bg-info)',
          'bg-info-hover': 'var(--color-bg-info-hover)',
          'bg-info-active': 'var(--color-bg-info-active)',
          'bg-info-selected': 'var(--color-bg-info-selected)',
          'bg-info-subtle': 'var(--color-bg-info-subtle)',
          'bg-info-subtlest': 'var(--color-bg-info-subtlest)',
          'bg-discovery': 'var(--color-bg-discovery)',
          'bg-discovery-hover': 'var(--color-bg-discovery-hover)',
          'bg-discovery-active': 'var(--color-bg-discovery-active)',
          'bg-discovery-selected': 'var(--color-bg-discovery-selected)',
          'bg-discovery-subtle': 'var(--color-bg-discovery-subtle)',
          'bg-discovery-subtlest': 'var(--color-bg-discovery-subtlest)',
          text: 'var(--color-text)',
          'text-description': 'var(--color-text-description)',
          'text-placeholder': 'var(--color-text-placeholder)',
          'text-disabled': 'var(--color-text-disabled)',
          'text-inverse': 'var(--color-text-inverse)',
          'text-brand': 'var(--color-text-brand)',
          'text-brand-hover': 'var(--color-text-brand-hover)',
          'text-brand-active': 'var(--color-text-brand-active)',
          'text-brand-inverse': 'var(--color-text-brand-inverse)',
          'text-brand-strong': 'var(--color-text-brand-strong)',
          'text-danger': 'var(--color-text-danger)',
          'text-danger-hover': 'var(--color-text-danger-hover)',
          'text-danger-active': 'var(--color-text-danger-active)',
          'text-danger-inverse': 'var(--color-text-danger-inverse)',
          'text-danger-strong': 'var(--color-text-danger-strong)',
          'text-warning': 'var(--color-text-warning)',
          'text-warning-hover': 'var(--color-text-warning-hover)',
          'text-warning-active': 'var(--color-text-warning-active)',
          'text-warning-inverse': 'var(--color-text-warning-inverse)',
          'text-warning-strong': 'var(--color-text-warning-strong)',
          'text-success': 'var(--color-text-success)',
          'text-success-hover': 'var(--color-text-success-hover)',
          'text-success-active': 'var(--color-text-success-active)',
          'text-success-inverse': 'var(--color-text-success-inverse)',
          'text-success-strong': 'var(--color-text-success-strong)',
          'text-info': 'var(--color-text-info)',
          'text-info-hover': 'var(--color-text-info-hover)',
          'text-info-active': 'var(--color-text-info-active)',
          'text-info-inverse': 'var(--color-text-info-inverse)',
          'text-info-strong': 'var(--color-text-info-strong)',
          'text-discovery': 'var(--color-text-discovery)',
          'text-discovery-hover': 'var(--color-text-discovery-hover)',
          'text-discovery-active': 'var(--color-text-discovery-active)',
          'text-discovery-inverse': 'var(--color-text-discovery-inverse)',
          'text-discovery-strong': 'var(--color-text-discovery-strong)',
          'border-primary': 'var(--color-border-primary)',
          'border-primary-hover': 'var(--color-border-primary-hover)',
          'border-primary-disabled': 'var(--color-border-primary-disabled)',
          'border-secondary': 'var(--color-border-secondary)',
          'border-brand': 'var(--color-border-brand)',
          'border-brand-hover': 'var(--color-border-brand-hover)',
          'border-brand-active': 'var(--color-border-brand-active)',
          'border-brand-subtle': 'var(--color-border-brand-subtle)',
          'border-brand-subtlest': 'var(--color-border-brand-subtlest)',
          'border-danger': 'var(--color-border-danger)',
          'border-danger-hover': 'var(--color-border-danger-hover)',
          'border-danger-active': 'var(--color-border-danger-active)',
          'border-danger-subtle': 'var(--color-border-danger-subtle)',
          'border-danger-subtlest': 'var(--color-border-danger-subtlest)',
          'border-warning': 'var(--color-border-warning)',
          'border-warning-hover': 'var(--color-border-warning-hover)',
          'border-warning-active': 'var(--color-border-warning-active)',
          'border-warning-subtle': 'var(--color-border-warning-subtle)',
          'border-warning-subtlest': 'var(--color-border-warning-subtlest)',
          'border-success': 'var(--color-border-success)',
          'border-success-hover': 'var(--color-border-success-hover)',
          'border-success-active': 'var(--color-border-success-active)',
          'border-success-subtle': 'var(--color-border-success-subtle)',
          'border-success-subtlest': 'var(--color-border-success-subtlest)',
          'border-info': 'var(--color-border-info)',
          'border-info-hover': 'var(--color-border-info-hover)',
          'border-info-active': 'var(--color-border-info-active)',
          'border-info-subtle': 'var(--color-border-info-subtle)',
          'border-info-subtlest': 'var(--color-border-info-subtlest)',
          'border-discovery': 'var(--color-border-discovery)',
          'border-discovery-hover': 'var(--color-border-discovery-hover)',
          'border-discovery-active': 'var(--color-border-discovery-active)',
          'border-discovery-subtle': 'var(--color-border-discovery-subtle)',
          'border-discovery-subtlest': 'var(--color-border-discovery-subtlest)',
          icon: 'var(--color-icon)',
          'icon-hover': 'var(--color-icon-hover)',
          'icon-active': 'var(--color-icon-active)',
          'icon-disabled': 'var(--color-icon-disabled)',
          'icon-inverse': 'var(--color-icon-inverse)',
          'icon-brand': 'var(--color-icon-brand)',
          'icon-brand-hover': 'var(--color-icon-brand-hover)',
          'icon-brand-active': 'var(--color-icon-brand-active)',
          'icon-brand-disabled': 'var(--color-icon-brand-disabled)',
          'icon-brand-strong': 'var(--color-icon-brand-strong)',
          'icon-brand-inverse': 'var(--color-icon-brand-inverse)',
          'icon-danger': 'var(--color-icon-danger)',
          'icon-danger-hover': 'var(--color-icon-danger-hover)',
          'icon-danger-active': 'var(--color-icon-danger-active)',
          'icon-danger-disabled': 'var(--color-icon-danger-disabled)',
          'icon-danger-strong': 'var(--color-icon-danger-strong)',
          'icon-danger-inverse': 'var(--color-icon-danger-inverse)',
          'icon-warning': 'var(--color-icon-warning)',
          'icon-warning-hover': 'var(--color-icon-warning-hover)',
          'icon-warning-active': 'var(--color-icon-warning-active)',
          'icon-warning-disabled': 'var(--color-icon-warning-disabled)',
          'icon-warning-strong': 'var(--color-icon-warning-strong)',
          'icon-warning-inverse': 'var(--color-icon-warning-inverse)',
          'icon-success': 'var(--color-icon-success)',
          'icon-success-hover': 'var(--color-icon-success-hover)',
          'icon-success-active': 'var(--color-icon-success-active)',
          'icon-success-disabled': 'var(--color-icon-success-disabled)',
          'icon-success-strong': 'var(--color-icon-success-strong)',
          'icon-success-inverse': 'var(--color-icon-success-inverse)',
          'icon-info': 'var(--color-icon-info)',
          'icon-info-hover': 'var(--color-icon-info-hover)',
          'icon-info-active': 'var(--color-icon-info-active)',
          'icon-info-disabled': 'var(--color-icon-info-disabled)',
          'icon-info-strong': 'var(--color-icon-info-strong)',
          'icon-info-inverse': 'var(--color-icon-info-inverse)',
          'icon-discovery': 'var(--color-icon-discovery)',
          'icon-discovery-hover': 'var(--color-icon-discovery-hover)',
          'icon-discovery-active': 'var(--color-icon-discovery-active)',
          'icon-discovery-disabled': 'var(--color-icon-discovery-disabled)',
          'icon-discovery-strong': 'var(--color-icon-discovery-strong)',
          'icon-discovery-inverse': 'var(--color-icon-discovery-inverse)',
        },
      },
      spacing: {
        px: '1px',
        0: 'var(--space-0)',
        1: 'var(--space-1)',
        2: 'var(--space-2)',
        3: 'var(--space-3)',
        4: 'var(--space-4)',
        5: 'var(--space-5)',
        6: 'var(--space-6)',
        8: 'var(--space-8)',
        10: 'var(--space-10)',
        12: 'var(--space-12)',
        16: 'var(--space-16)',
        20: 'var(--space-20)',
        24: 'var(--space-24)',
        28: 'var(--space-28)',
        32: 'var(--space-32)',
        36: 'var(--space-36)',
        40: 'var(--space-40)',
      },
      borderRadius: {
        'radius-none': 'var(--border-radius-none)',
        'radius-sm': 'var(--border-radius-sm)',
        radius: 'var(--border-radius)',
        'radius-lg': 'var(--border-radius-lg)',
        'radius-full': 'var(--border-radius-full)',
      },
      width: {
        xs: 'var(--size-width-xs)',
        sm: 'var(--size-width-sm)',
        DEFAULT: 'var(--size-width)',
        lg: 'var(--size-width-lg)',
      },
      height: {
        xs: 'var(--size-height-xs)',
        sm: 'var(--size-height-sm)',
        DEFAULT: 'var(--height-width)',
        lg: 'var(--size-height-lg)',
      },
    },
  },
  plugins: [],
};
