name: Build Design Tokens

on:
  push:
    paths:
      - 'design-tokens/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2.4.0

    - run: npm install
      working-directory: ./design-tokens

    - run: npm run build
      working-directory: ./design-tokens

    - name: Commit and Push Changes
      run: |
        git config user.name "kkratterf"
        git config user.email "kkratterf@gmail.com"
        git add .
        git commit -m "Update token"
        git push
      working-directory: ./design-tokens